### ISSUE TITLE
Cannot log multiple batches with a single session

### ISSUE THREAD

**Issue by ibackus** [whylabs/whylogs#13]
I've got a list of dataframes, each representing a batch of data, each with a different corresponding data timestamp.  
I should be able to, with a single session, log each of them independently, but I cannot.

# Example

```yaml
# .whylogs.yaml

# Example WhyLogs YAML configuration
project: example-project
pipeline: example-pipeline
verbose: false
writers:
# Save out the full protobuf datasketches data locally
- formats:
    - protobuf
  output_path: whylogs-output
  # Template variables can be accessed via $variable or ${variable}
  path_template: $name/dataset_profile
  filename_template: datase_profile-$dataset_timestamp
  type: local
# Save out the flat summary data locally, separately from the protobuf
- formats:
    - flat
    - json
  output_path: whylogs-output
  path_template: $name/dataset_summary
  filename_template: dataset_summary-$dataset_timestamp
  type: local
```

## Code

```python
from whylogs.app.session import get_or_create_session, reset_session

# Just make sure no previous session is active
reset_session()

# Load config from disk and return the active session
session = get_or_create_session()
```

```
for df in data_batches:
    data_timestamp = df['issue_d'].max()
    print('Data batch timestamp:', data_timestamp)
    with session.logger(dataset_timestamp=data_timestamp) as ylog:
        ylog.log_dataframe(df)
```

### Output:
```
Data batch timestamp: 2020-08-26 00:00:00
WARNING: attempting to close a closed logger
Data batch timestamp: 2020-08-27 00:00:00
WARNING: attempting to close a closed logger
Data batch timestamp: 2020-08-28 00:00:00
WARNING: attempting to close a closed logger
Data batch timestamp: 2020-08-29 00:00:00
WARNING: attempting to close a closed logger
Data batch timestamp: 2020-08-30 00:00:00
WARNING: attempting to close a closed logger
Data batch timestamp: 2020-08-31 00:00:00
WARNING: attempting to close a closed logger
```

Additionally, only one set of files is generated, rather than 1 per batch:

```bash
ibackus@WhyLabs-Isaac:$ tree whylogs-output/
whylogs-output/
└── example-project
    ├── dataset_profile
    │   └── protobuf
    │       └── datase_profile-1598400000000.bin
    └── dataset_summary
        ├── flat_table
        │   └── dataset_summary-1598400000000.csv
        ├── freq_numbers
        │   └── dataset_summary-1598400000000.json
        ├── frequent_strings
        │   └── dataset_summary-1598400000000.json
        ├── histogram
        │   └── dataset_summary-1598400000000.json
        └── json
            └── dataset_summary-1598400000000.json

9 directories, 6 files
```
